global:
  scrape_interval: 15s

scrape_configs:
  - job_name: ingestion
    metrics_path: /metrics
    static_configs:
      - targets: ["ingestion:8001"]
  - job_name: admin
    metrics_path: /metrics/prometheus
    static_configs:
      - targets: ["admin:8002"]
  - job_name: alerts
    metrics_path: /metrics
    static_configs:
      - targets: ["alerts:8003"]
